---
# This playbook contains common plays that will be run on all nodes.

- include: selenium_check.yml
  when: selenium_enabled 
  tags: [selenium]
  
- include: selenium_install.yml
  when: selenium_needs_install is defined
  tags: [selenium]

- include: selenium_chromedriver.yml
  when: chromedriver_needs_install is defined
  tags: [chromedriver]

- name: Copy Dockerfile
  template: src=Dockerfile.j2 dest={{ docker_files_generated_directory }}/Dockerfile mode=0777
  when: docker_files_enable
  
- name: Copy build.sh
  template: src=build.sh.j2 dest={{ docker_files_generated_directory }}/build.sh mode=0777
  when: docker_files_enable
