---
# This playbook contains common plays that will be run on all nodes.

- name: selenium | Create temporary directory
  shell: mktemp -d
  register: tempdir
  sudo: true
  tags: selenium_setup

- name: selenium | Download selenium on 'master' if we don't have it
  sudo: False
  get_url: url={{ selenium_download_url }}  dest={{ selenium_dir_tmp }}/{{ selenium_jar_file }} force=no
  tags: selenium_setup

- name: selenium | Copy selenium into place
  command: mv {{ selenium_dir_tmp }}/{{ selenium_jar_file }} {{ selenium_install_path }} creates="{{ selenium_install_path }}"
  tags: selenium_setup

- name: selenium | Ensure permissions
  file: path="{{ selenium_install_path }}" state=file owner=root group=root mode=0755
  tags: selenium_setup

- name: selenium | Install Configuration
  template: src=defaults.j2 dest=/etc/default/selenium_{{ selenium_sel_role }} owner=root group=root mode=644
  tags: ['config']
  notify: selenium_reload

- name: selenium | Install init script
  template: src=selenium-server.sh.j2 dest=/etc/init.d/selenium_{{ selenium_sel_role }} owner=root group=root mode=755
  tags: ['config']
  notify: selenium_started

- name: selenium | Install run scripts
  template: src="{{item}}.tpl" dest="/usr/local/bin/{{item}}" owner=root group=root mode='0755'
  tags: ['config']
  with_items:
  - 'run_selenium_hub.sh'

- name: selenium | Install selenium tools
  apt: pkg={{ item }} state={{ selenium_pkg_state }} update_cache=yes
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( selenium_sel_role != 'hub' )
  with_items:
   - xfonts-100dpi
   - xfonts-75dpi
   - xfonts-scalable
   - xfonts-cyrillic
   - xvfb
   - x11-apps
   - imagemagick
